# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bot_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bot_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbot_api.proto\x12\x07\x62ot_api\"2\n\x11GetUpdatesRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\r\n\x05limit\x18\x02 \x01(\x05\"Z\n\tBotUpdate\x12\x12\n\nmessage_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"9\n\x12GetUpdatesResponse\x12#\n\x07updates\x18\x01 \x03(\x0b\x32\x12.bot_api.BotUpdate\"9\n\x12SendMessageRequest\x12\x12\n\nto_user_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\")\n\x13SendMessageResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\x03\x32\xa0\x01\n\rBotApiService\x12\x45\n\nGetUpdates\x12\x1a.bot_api.GetUpdatesRequest\x1a\x1b.bot_api.GetUpdatesResponse\x12H\n\x0bSendMessage\x12\x1b.bot_api.SendMessageRequest\x1a\x1c.bot_api.SendMessageResponseBDZBgithub.com/magomedcoder/haratsan-sdk/go/gen_pb/bot_apipb;bot_apipbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/magomedcoder/haratsan-sdk/go/gen_pb/bot_apipb;bot_apipb'
  _globals['_GETUPDATESREQUEST']._serialized_start=26
  _globals['_GETUPDATESREQUEST']._serialized_end=76
  _globals['_BOTUPDATE']._serialized_start=78
  _globals['_BOTUPDATE']._serialized_end=168
  _globals['_GETUPDATESRESPONSE']._serialized_start=170
  _globals['_GETUPDATESRESPONSE']._serialized_end=227
  _globals['_SENDMESSAGEREQUEST']._serialized_start=229
  _globals['_SENDMESSAGEREQUEST']._serialized_end=286
  _globals['_SENDMESSAGERESPONSE']._serialized_start=288
  _globals['_SENDMESSAGERESPONSE']._serialized_end=329
  _globals['_BOTAPISERVICE']._serialized_start=332
  _globals['_BOTAPISERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
