# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bot_api_pb2 as bot__api__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bot_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BotApiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUpdates = channel.unary_unary(
                '/bot_api.BotApiService/GetUpdates',
                request_serializer=bot__api__pb2.GetUpdatesRequest.SerializeToString,
                response_deserializer=bot__api__pb2.GetUpdatesResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/bot_api.BotApiService/SendMessage',
                request_serializer=bot__api__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=bot__api__pb2.SendMessageResponse.FromString,
                _registered_method=True)


class BotApiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdates,
                    request_deserializer=bot__api__pb2.GetUpdatesRequest.FromString,
                    response_serializer=bot__api__pb2.GetUpdatesResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=bot__api__pb2.SendMessageRequest.FromString,
                    response_serializer=bot__api__pb2.SendMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bot_api.BotApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bot_api.BotApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotApiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bot_api.BotApiService/GetUpdates',
            bot__api__pb2.GetUpdatesRequest.SerializeToString,
            bot__api__pb2.GetUpdatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bot_api.BotApiService/SendMessage',
            bot__api__pb2.SendMessageRequest.SerializeToString,
            bot__api__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
