# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bot_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bot_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbot_api.proto\x12\x07\x62ot_api\"K\n\x11GetUpdatesRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x17\n\x0f\x63\x61llback_offset\x18\x03 \x01(\x03\"Z\n\tBotUpdate\x12\x12\n\nmessage_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"s\n\x10\x42otCallbackQuery\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\x03\x12\x12\n\nmessage_id\x18\x03 \x01(\x03\x12\x15\n\rcallback_data\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"n\n\x12GetUpdatesResponse\x12#\n\x07updates\x18\x01 \x03(\x0b\x32\x12.bot_api.BotUpdate\x12\x33\n\x10\x63\x61llback_queries\x18\x02 \x03(\x0b\x32\x19.bot_api.BotCallbackQuery\";\n\x14InlineKeyboardButton\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rcallback_data\x18\x02 \x01(\t\"C\n\x11InlineKeyboardRow\x12.\n\x07\x62uttons\x18\x01 \x03(\x0b\x32\x1d.bot_api.InlineKeyboardButton\"B\n\x0bReplyMarkup\x12\x33\n\x0finline_keyboard\x18\x01 \x03(\x0b\x32\x1a.bot_api.InlineKeyboardRow\"e\n\x12SendMessageRequest\x12\x12\n\nto_user_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12*\n\x0creply_markup\x18\x03 \x01(\x0b\x32\x14.bot_api.ReplyMarkup\")\n\x13SendMessageResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\x03\x32\xa0\x01\n\rBotApiService\x12\x45\n\nGetUpdates\x12\x1a.bot_api.GetUpdatesRequest\x1a\x1b.bot_api.GetUpdatesResponse\x12H\n\x0bSendMessage\x12\x1b.bot_api.SendMessageRequest\x1a\x1c.bot_api.SendMessageResponseBDZBgithub.com/magomedcoder/haratsan-sdk/go/gen_pb/bot_apipb;bot_apipbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/magomedcoder/haratsan-sdk/go/gen_pb/bot_apipb;bot_apipb'
  _globals['_GETUPDATESREQUEST']._serialized_start=26
  _globals['_GETUPDATESREQUEST']._serialized_end=101
  _globals['_BOTUPDATE']._serialized_start=103
  _globals['_BOTUPDATE']._serialized_end=193
  _globals['_BOTCALLBACKQUERY']._serialized_start=195
  _globals['_BOTCALLBACKQUERY']._serialized_end=310
  _globals['_GETUPDATESRESPONSE']._serialized_start=312
  _globals['_GETUPDATESRESPONSE']._serialized_end=422
  _globals['_INLINEKEYBOARDBUTTON']._serialized_start=424
  _globals['_INLINEKEYBOARDBUTTON']._serialized_end=483
  _globals['_INLINEKEYBOARDROW']._serialized_start=485
  _globals['_INLINEKEYBOARDROW']._serialized_end=552
  _globals['_REPLYMARKUP']._serialized_start=554
  _globals['_REPLYMARKUP']._serialized_end=620
  _globals['_SENDMESSAGEREQUEST']._serialized_start=622
  _globals['_SENDMESSAGEREQUEST']._serialized_end=723
  _globals['_SENDMESSAGERESPONSE']._serialized_start=725
  _globals['_SENDMESSAGERESPONSE']._serialized_end=766
  _globals['_BOTAPISERVICE']._serialized_start=769
  _globals['_BOTAPISERVICE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
