// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: bot_api.proto

package bot_apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUpdatesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Offset         int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	CallbackOffset int64                  `protobuf:"varint,3,opt,name=callback_offset,json=callbackOffset,proto3" json:"callback_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUpdatesRequest) Reset() {
	*x = GetUpdatesRequest{}
	mi := &file_bot_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesRequest) ProtoMessage() {}

func (x *GetUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesRequest.ProtoReflect.Descriptor instead.
func (*GetUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetUpdatesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUpdatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUpdatesRequest) GetCallbackOffset() int64 {
	if x != nil {
		return x.CallbackOffset
	}
	return 0
}

type BotUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotUpdate) Reset() {
	*x = BotUpdate{}
	mi := &file_bot_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotUpdate) ProtoMessage() {}

func (x *BotUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotUpdate.ProtoReflect.Descriptor instead.
func (*BotUpdate) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{1}
}

func (x *BotUpdate) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *BotUpdate) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *BotUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BotUpdate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type BotCallbackQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CallbackData  string                 `protobuf:"bytes,4,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotCallbackQuery) Reset() {
	*x = BotCallbackQuery{}
	mi := &file_bot_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotCallbackQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCallbackQuery) ProtoMessage() {}

func (x *BotCallbackQuery) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCallbackQuery.ProtoReflect.Descriptor instead.
func (*BotCallbackQuery) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{2}
}

func (x *BotCallbackQuery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BotCallbackQuery) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *BotCallbackQuery) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *BotCallbackQuery) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

func (x *BotCallbackQuery) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetUpdatesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Updates         []*BotUpdate           `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	CallbackQueries []*BotCallbackQuery    `protobuf:"bytes,2,rep,name=callback_queries,json=callbackQueries,proto3" json:"callback_queries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUpdatesResponse) Reset() {
	*x = GetUpdatesResponse{}
	mi := &file_bot_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesResponse) ProtoMessage() {}

func (x *GetUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetUpdatesResponse) GetUpdates() []*BotUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *GetUpdatesResponse) GetCallbackQueries() []*BotCallbackQuery {
	if x != nil {
		return x.CallbackQueries
	}
	return nil
}

type InlineKeyboardButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CallbackData  string                 `protobuf:"bytes,2,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineKeyboardButton) Reset() {
	*x = InlineKeyboardButton{}
	mi := &file_bot_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKeyboardButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardButton) ProtoMessage() {}

func (x *InlineKeyboardButton) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardButton.ProtoReflect.Descriptor instead.
func (*InlineKeyboardButton) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{4}
}

func (x *InlineKeyboardButton) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InlineKeyboardButton) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

type InlineKeyboardRow struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Buttons       []*InlineKeyboardButton `protobuf:"bytes,1,rep,name=buttons,proto3" json:"buttons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineKeyboardRow) Reset() {
	*x = InlineKeyboardRow{}
	mi := &file_bot_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKeyboardRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardRow) ProtoMessage() {}

func (x *InlineKeyboardRow) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardRow.ProtoReflect.Descriptor instead.
func (*InlineKeyboardRow) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{5}
}

func (x *InlineKeyboardRow) GetButtons() []*InlineKeyboardButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

type ReplyMarkup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InlineKeyboard []*InlineKeyboardRow   `protobuf:"bytes,1,rep,name=inline_keyboard,json=inlineKeyboard,proto3" json:"inline_keyboard,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplyMarkup) Reset() {
	*x = ReplyMarkup{}
	mi := &file_bot_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMarkup) ProtoMessage() {}

func (x *ReplyMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMarkup.ProtoReflect.Descriptor instead.
func (*ReplyMarkup) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyMarkup) GetInlineKeyboard() []*InlineKeyboardRow {
	if x != nil {
		return x.InlineKeyboard
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUserId      int64                  `protobuf:"varint,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ReplyMarkup   *ReplyMarkup           `protobuf:"bytes,3,opt,name=reply_markup,json=replyMarkup,proto3" json:"reply_markup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_bot_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetReplyMarkup() *ReplyMarkup {
	if x != nil {
		return x.ReplyMarkup
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_bot_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_bot_api_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_bot_api_proto protoreflect.FileDescriptor

const file_bot_api_proto_rawDesc = "" +
	"\n" +
	"\rbot_api.proto\x12\abot_api\"j\n" +
	"\x11GetUpdatesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12'\n" +
	"\x0fcallback_offset\x18\x03 \x01(\x03R\x0ecallbackOffset\"\x85\x01\n" +
	"\tBotUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\xa7\x01\n" +
	"\x10BotCallbackQuery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12#\n" +
	"\rcallback_data\x18\x04 \x01(\tR\fcallbackData\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x88\x01\n" +
	"\x12GetUpdatesResponse\x12,\n" +
	"\aupdates\x18\x01 \x03(\v2\x12.bot_api.BotUpdateR\aupdates\x12D\n" +
	"\x10callback_queries\x18\x02 \x03(\v2\x19.bot_api.BotCallbackQueryR\x0fcallbackQueries\"O\n" +
	"\x14InlineKeyboardButton\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rcallback_data\x18\x02 \x01(\tR\fcallbackData\"L\n" +
	"\x11InlineKeyboardRow\x127\n" +
	"\abuttons\x18\x01 \x03(\v2\x1d.bot_api.InlineKeyboardButtonR\abuttons\"R\n" +
	"\vReplyMarkup\x12C\n" +
	"\x0finline_keyboard\x18\x01 \x03(\v2\x1a.bot_api.InlineKeyboardRowR\x0einlineKeyboard\"\x85\x01\n" +
	"\x12SendMessageRequest\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\x03R\btoUserId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x127\n" +
	"\freply_markup\x18\x03 \x01(\v2\x14.bot_api.ReplyMarkupR\vreplyMarkup\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId2\xa0\x01\n" +
	"\rBotApiService\x12E\n" +
	"\n" +
	"GetUpdates\x12\x1a.bot_api.GetUpdatesRequest\x1a\x1b.bot_api.GetUpdatesResponse\x12H\n" +
	"\vSendMessage\x12\x1b.bot_api.SendMessageRequest\x1a\x1c.bot_api.SendMessageResponseBDZBgithub.com/magomedcoder/haratsan-sdk/go/gen_pb/bot_apipb;bot_apipbb\x06proto3"

var (
	file_bot_api_proto_rawDescOnce sync.Once
	file_bot_api_proto_rawDescData []byte
)

func file_bot_api_proto_rawDescGZIP() []byte {
	file_bot_api_proto_rawDescOnce.Do(func() {
		file_bot_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_api_proto_rawDesc), len(file_bot_api_proto_rawDesc)))
	})
	return file_bot_api_proto_rawDescData
}

var file_bot_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bot_api_proto_goTypes = []any{
	(*GetUpdatesRequest)(nil),    // 0: bot_api.GetUpdatesRequest
	(*BotUpdate)(nil),            // 1: bot_api.BotUpdate
	(*BotCallbackQuery)(nil),     // 2: bot_api.BotCallbackQuery
	(*GetUpdatesResponse)(nil),   // 3: bot_api.GetUpdatesResponse
	(*InlineKeyboardButton)(nil), // 4: bot_api.InlineKeyboardButton
	(*InlineKeyboardRow)(nil),    // 5: bot_api.InlineKeyboardRow
	(*ReplyMarkup)(nil),          // 6: bot_api.ReplyMarkup
	(*SendMessageRequest)(nil),   // 7: bot_api.SendMessageRequest
	(*SendMessageResponse)(nil),  // 8: bot_api.SendMessageResponse
}
var file_bot_api_proto_depIdxs = []int32{
	1, // 0: bot_api.GetUpdatesResponse.updates:type_name -> bot_api.BotUpdate
	2, // 1: bot_api.GetUpdatesResponse.callback_queries:type_name -> bot_api.BotCallbackQuery
	4, // 2: bot_api.InlineKeyboardRow.buttons:type_name -> bot_api.InlineKeyboardButton
	5, // 3: bot_api.ReplyMarkup.inline_keyboard:type_name -> bot_api.InlineKeyboardRow
	6, // 4: bot_api.SendMessageRequest.reply_markup:type_name -> bot_api.ReplyMarkup
	0, // 5: bot_api.BotApiService.GetUpdates:input_type -> bot_api.GetUpdatesRequest
	7, // 6: bot_api.BotApiService.SendMessage:input_type -> bot_api.SendMessageRequest
	3, // 7: bot_api.BotApiService.GetUpdates:output_type -> bot_api.GetUpdatesResponse
	8, // 8: bot_api.BotApiService.SendMessage:output_type -> bot_api.SendMessageResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bot_api_proto_init() }
func file_bot_api_proto_init() {
	if File_bot_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_api_proto_rawDesc), len(file_bot_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_api_proto_goTypes,
		DependencyIndexes: file_bot_api_proto_depIdxs,
		MessageInfos:      file_bot_api_proto_msgTypes,
	}.Build()
	File_bot_api_proto = out.File
	file_bot_api_proto_goTypes = nil
	file_bot_api_proto_depIdxs = nil
}
